Add loadash in the header
ReferenceError: _ is not defined from npm import. Need to define loadash to prevent this error as this dependency is required for Zoom SDK.